[project]
name = "bazel-simple-python"
version = "0.2.0"
description = "Projeto de Exemplo: Monorepo com Python e Bazel"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
]
