[project]
name = "macro-dag"
version = "0.1.0"
description = "UV workspace com acesso a lib externa"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mylib",
]

[tool.uv.sources]
mylib = { workspace = true }
